Aplicacion BDPeluqueria/Controllers/BD/Casa_ComercController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aplicacion_BDPeluqueria.BaseDatos;
using Aplicacion_BDPeluqueria.Models.CasasComerciales;
using AutoMapper;

namespace Aplicacion_BDPeluqueria.Controllers
{
    public class Casa_ComercController : Controller
    {
        private BDPeluqueriaEntities1 db = new BDPeluqueriaEntities1();

        // GET: Casa_Comerc
        public ActionResult Index()
        {
            var casas = db.Casa_Comerc;
            var modelos = Mapper.Map<IEnumerable<Casa_Comerc>, IEnumerable<InfoCasa>>(casas);

            return View(modelos);
        }

        // GET: Casa_Comerc/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Casa_Comerc casa_Comerc = db.Casa_Comerc.Find(id);
            if (casa_Comerc == null)
            {
                return HttpNotFound();
            }
            return View(casa_Comerc);
        }

        // GET: Casa_Comerc/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Casa_Comerc/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nombre_Casa,local_Casa")] Casa_Comerc casa_Comerc)
        {

            if (ModelState.IsValid)
            {
                db.Casa_Comerc.Add(casa_Comerc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(casa_Comerc);
        }

        // GET: Casa_Comerc/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Casa_Comerc casa_Comerc = db.Casa_Comerc.Find(id);
            if (casa_Comerc == null)
            {
                return HttpNotFound();
            }
            return View(casa_Comerc);
        }

        // POST: Casa_Comerc/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nombre_Casa,local_Casa")] Casa_Comerc casa_Comerc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(casa_Comerc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(casa_Comerc);
        }

        // GET: Casa_Comerc/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Casa_Comerc casa_Comerc = db.Casa_Comerc.Find(id);
            if (casa_Comerc == null)
            {
                return HttpNotFound();
            }
            return View(casa_Comerc);
        }

        // POST: Casa_Comerc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Casa_Comerc casa_Comerc = db.Casa_Comerc.Find(id);
            db.Casa_Comerc.Remove(casa_Comerc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aplicacion BDPeluqueria/Controllers/BD/Res_ProdController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aplicacion_BDPeluqueria.BaseDatos;

namespace Aplicacion_BDPeluqueria.Controllers
{
    public class Res_ProdController : Controller
    {
        private BDPeluqueriaEntities1 db = new BDPeluqueriaEntities1();

        // GET: Res_Prod
        public ActionResult Index()
        {
            var res_Prod = db.Res_Prod.Include(r => r.Producto).Include(r => r.Reserva);
            return View(res_Prod.ToList());
        }

        // GET: Res_Prod/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Res_Prod res_Prod = db.Res_Prod.Find(id);
            if (res_Prod == null)
            {
                return HttpNotFound();
            }
            return View(res_Prod);
        }

        // GET: Res_Prod/Create
        public ActionResult Create()
        {
            ViewBag.id_Prod = new SelectList(db.Productos, "id_Prod", "nombre_Prod");
            ViewBag.num_Res = new SelectList(db.Reservas, "num_Res", "dni_Cli");
            return View();
        }

        // POST: Res_Prod/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "num_Res,id_Prod,cantidad")] Res_Prod res_Prod)
        {
            if (ModelState.IsValid)
            {
                db.Res_Prod.Add(res_Prod);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_Prod = new SelectList(db.Productos, "id_Prod", "nombre_Prod", res_Prod.id_Prod);
            ViewBag.num_Res = new SelectList(db.Reservas, "num_Res", "dni_Cli", res_Prod.num_Res);
            return View(res_Prod);
        }

        // GET: Res_Prod/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Res_Prod res_Prod = db.Res_Prod.Find(id);
            if (res_Prod == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_Prod = new SelectList(db.Productos, "id_Prod", "nombre_Prod", res_Prod.id_Prod);
            ViewBag.num_Res = new SelectList(db.Reservas, "num_Res", "dni_Cli", res_Prod.num_Res);
            return View(res_Prod);
        }

        // POST: Res_Prod/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "num_Res,id_Prod,cantidad")] Res_Prod res_Prod)
        {
            if (ModelState.IsValid)
            {
                db.Entry(res_Prod).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_Prod = new SelectList(db.Productos, "id_Prod", "nombre_Prod", res_Prod.id_Prod);
            ViewBag.num_Res = new SelectList(db.Reservas, "num_Res", "dni_Cli", res_Prod.num_Res);
            return View(res_Prod);
        }

        // GET: Res_Prod/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Res_Prod res_Prod = db.Res_Prod.Find(id);
            if (res_Prod == null)
            {
                return HttpNotFound();
            }
            return View(res_Prod);
        }

        // POST: Res_Prod/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Res_Prod res_Prod = db.Res_Prod.Find(id);
            db.Res_Prod.Remove(res_Prod);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aplicacion BDPeluqueria/Views/Shared/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Aplicacion BDPeluqueria/Views/Shared/_Header.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> @ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header id="MainNavbar" class="main-header">

        <nav class="navbar navbar-expand-lg alert alert-warning" style="margin-right:20px">
            <a href="@Url.Action("Index","Home", new { area = "" })" class="logo">
                <span class="logo" style="font-size:30px"> <b> <u>P</u>eluqueria <u>L</u>azo's </b></span>
            </a>

            <div>
                <ul class="nav nav-tabs" style="margin-left:30px">


                    <li routerlinkactive="active" class="active" id="peluqueros" >
                        <a data-toggle="collapse" href="#Peluqueros" class="collapsed" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            Peluqueros <span class="sr-only">(current)</span>
                        </a>
                        <div class="collapse" id="Peluqueros" aria-expanded="false" style="height: 0px;">

                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Create", "Peluqueros", new { area = "" })">
                                        <i class="fa fa-users"></i><span>Añadir</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Peluqueros", new { area = "" })">
                                        <i class="fa fa-th-large"></i><span>Registro</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li routerlinkactive="active" class="active" id="clientes" style="margin-left:30px">
                        <a data-toggle="collapse" href="#Clientes" class="collapsed" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            Clientes <span class="sr-only">(current)</span>
                        </a>
                        <div class="collapse" id="Clientes" aria-expanded="false" style="height: 0px;">

                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Create", "Clientes", new { area = "" })">
                                        <i class="fa fa-users"></i><span>Añadir </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Clientes", new { area = "" })">
                                        <i class="fa fa-th-large"></i><span>Registro </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li routerlinkactive="active" class="active" id="productos" style="margin-left:30px">
                        <a data-toggle="collapse" href="#Productos" class="collapsed" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            Productos <span class="sr-only">(current)</span>
                        </a>
                        <div class="collapse" id="Productos" aria-expanded="false" style="height: 0px;">

                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Create", "Productos", new { area = "" })">
                                        <i class="fa fa-users"></i><span>Añadir</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Productos", new { area = "" })">
                                        <i class="fa fa-th-large"></i><span>Registro </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li routerlinkactive="active" class="active" id="reservas" style="margin-left:30px">
                        <a data-toggle="collapse" href="#Reservas" class="collapsed" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            Reservas <span class="sr-only">(current)</span>
                        </a>
                        <div class="collapse" id="Reservas" aria-expanded="false" style="height: 0px;">

                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Create", "Reservas", new { area = "" })">
                                        <i class="fa fa-users"></i><span>Añadir</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Reservas", new { area = "" })">
                                        <i class="fa fa-th-large"></i><span>Registro</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li routerlinkactive="active" class="active" id="casas" style="margin-left:30px">
                        <a data-toggle="collapse" href="#Casas" class="collapsed" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                            Casas Comerciales <span class="sr-only">(current)</span>
                        </a>
                        <div class="collapse" id="Casas" aria-expanded="false" style="height: 0px;">

                            <ul class="treeview-menu">
                                <li>
                                    <a href="@Url.Action("Create", "Casa_Comerc", new { area = "" })">
                                        <i class="fa fa-users"></i><span>Añadir</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Casa_Comerc", new { area = "" })">
                                        <i class="fa fa-th-large"></i><span>Registro</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>

            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="margin-left:40px">
                <button class="btn btn-outline-#fa8072 my-2 my-sm-0" type="submit">Search</button>
            </form>

            <div class="nav navbar-nav" style="margin-left:40px">
               
                    
                        <div>
                            <ul>
                                <li>
                                    <a href="@Url.Action("Registrar", "Usuarios", new { area = "" })">
                                        <i class="fa fa-th-large"></i><span>Cuenta</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    
                
                <span style="margin-right:20px"> <a href="/"> Salir </a>  </span>
            </div>
        </nav>
    </header>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

Aplicacion BDPeluqueria/Views/Shared/_Sidebar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> @ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrapper" style=" margin-left:30px">
        <header class="main-header">
          
        </header>
        <aside>

            <ul class="sidebar-menu">

                @*<li routerlinkactive="active" class="active" id="clientes">
                    <a data-toggle="collapse" href="#Clientes" class="collapsed" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        Clientes <span class="sr-only">(current)</span>
                    </a>
                    <div class="collapse" id="Clientes" aria-expanded="false" style="height: 0px;">

                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Create", "Clientes", new { area = "" })">
                                    <i class="fa fa-users"></i><span>Añadir</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Clientes", new { area = "" })">
                                    <i class="fa fa-th-large"></i><span>Datos </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Edit", "Clientes", new {area = ""})">
                                    <i class="fa  fa-file-text-o"></i><span>Modificar</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Delete", "Clientes", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span> Borrar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>*@

                @*<li routerlinkactive="active" class="active" id="peluqueros">
                    <a data-toggle="collapse" href="#Peluqueros" class="collapsed" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        Peluqueros <span class="sr-only">(current)</span>
                    </a>
                    <div class="collapse" id="Peluqueros" aria-expanded="false" style="height: 0px;">

                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Create", "Peluqueros", new { area = "" })">
                                    <i class="fa fa-users"></i><span>Añadir</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Peluqueros", new { area = "" })">
                                    <i class="fa fa-th-large"></i><span>Datos </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Edit", "Peluqueros", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span>Modificar</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Delete", "Peluqueros", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span> Borrar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>*@

                @*<li routerlinkactive="active" class="active" id="productos">
                    <a data-toggle="collapse" href="#Productos" class="collapsed" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        Productos <span class="sr-only">(current)</span>
                    </a>
                    <div class="collapse" id="Productos" aria-expanded="false" style="height: 0px;">

                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Create", "Productos", new { area = "" })">
                                    <i class="fa fa-users"></i><span>Añadir</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Productos", new { area = "" })">
                                    <i class="fa fa-th-large"></i><span>Datos </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Edit", "Productos", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span>Modificar</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Delete", "Productos", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span> Borrar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>*@
                @*<li routerlinkactive="active" class="active" id="reservas">
                    <a data-toggle="collapse" href="#Reservas" class="collapsed" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        Reservas <span class="sr-only">(current)</span>
                    </a>
                    <div class="collapse" id="Reservas" aria-expanded="false" style="height: 0px;">

                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Create", "Res_Prod", new { area = "" })">
                                    <i class="fa fa-users"></i><span>Añadir</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Res_Prod", new { area = "" })">
                                    <i class="fa fa-th-large"></i><span>Datos </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Edit", "Res_Prod", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span>Modificar</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Delete", "Res_Prod", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span> Borrar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>*@
                @*<li routerlinkactive="active" class="active" id="casas">
                    <a data-toggle="collapse" href="#Casas" class="collapsed" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        Casas Comerciales <span class="sr-only">(current)</span>
                    </a>
                    <div class="collapse" id="Casas" aria-expanded="false" style="height: 0px;">

                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Create", "Casa_Comerc", new { area = "" })">
                                    <i class="fa fa-users"></i><span>Añadir</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Casa_Comerc", new { area = "" })">
                                    <i class="fa fa-th-large"></i><span>Datos </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Edit", "Casa_Comerc", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span>Modificar</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Delete", "Casa_Comerc", new { area = "" })">
                                    <i class="fa  fa-file-text-o"></i><span> Borrar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>*@
                </ul>
            </aside>
        </div>
    </body>
</html>

            